name = "Novel Reader"
default_targets = ["win32"]
build_directory = "../build"

love_files = [
    "+*",
    "-./.git/*",
    "-./.github/*",
    "-./dist/*",
    "-./makelove.toml"    
]

icon_file = "./assets/app_logo.png"


[windows]

[archive_files]
# source = destination
# source is game root dir.
# destination is root dir in archived zip
"savedata.txt" = "savedata.txt"
"assets/book_files/compile.py" = "compile.py"
"assets/book_files/book.txt" = "book.txt"
"assets/book_files/book_compiled.txt" = "book_compiled.txt"


[windows.exe_metadata]
FileDescription = "Read Novels, VN Style."
FileVersion = "0.1"
OriginalFilename = "Novel Reader.exe" 





