name: Build Binaries.
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
        submodules: true
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install --assume-yes wine-stable wine64 python3-pip
    - name: Checkout makelove
      uses: actions/checkout@v2
      with:
        repository: pfirsich/makelove
        path: makelove
    - name: Install makelove
      run:
        pip3 install ./makelove
    - name: Build
      run: cd main/novel-reader && python3 -m makelove
    - name: Artifact (Win64)
    - run: sudo apt install tree -y && tree -L 10 && pwd
      uses: actions/upload-artifact@v2
      with:
        name: build win64 artifact
        path: main/build/win64/Novel Reader.exe
